%% Plotting data generated by nlmixr2
% When model fits are generated in nlmixr, the individual ANC predictions
% are stored in the IPRED column. We can use this data to establish the
% modelling error.

clear; clc; close all;

% Path to CSV file with patient data
treatmentCsvFilePath = "C:\Users\trent\UofT\Research\Leukemia\Code\Leukemia-PKPD\results\SimplifiedJostModel_20250723_123549\SimplifiedJostModel_20250723_123549_treatment.csv";
treatmentData = readtable(treatmentCsvFilePath);

patientIDs = unique(treatmentData.ID);

%% Plot Predictions vs Measured Data

% Select which patient to plot:
patientID = patientIDs(88);

% Measurement noise std (for error bars)
measNoiseStd = nan;

figure;
hold on;

mask = treatmentData.ID == patientID & treatmentData.EVID == 0;

t = treatmentData.TIME(mask);
ypred = treatmentData.IPRED(mask);
ytrue = treatmentData.DV(mask);

sim = plot(t, ypred, ...
    '-o', ...
    'Color','r', ...
    'DisplayName','Predicted');
true = errorbar(t, ytrue, ytrue.*measNoiseStd, ...
    '-o', ...
    'Color','b', ...
    'DisplayName','Measured');
legend;

%% Calculate statistics

numMeasurements = nnz(treatmentData.EVID == 0);

mask = treatmentData.EVID == 0;

t = treatmentData.TIME(mask);
ypred = treatmentData.IPRED(mask);
ytrue = treatmentData.DV(mask);

errors = ypred - ytrue;

% Calculate absolute errors
absErrors = abs(errors);

% Calculate squared errors
% sqdErrors = errors.^2;

meanAbsErrors = mean(absErrors)
stdAbsErrors = std(absErrors)
% meanSqdErrors = mean(sqdErrors);
% stdSqdErrors = std(sqdErrors);

%% Calculate RMSE for each patient

patientRMSEs = nan(size(patientIDs));
for i = 1:length(patientIDs)
    pid = patientIDs(i);
    mask = treatmentData.ID == pid & treatmentData.EVID == 0;
    ypred = treatmentData.IPRED(mask);
    ytrue = treatmentData.DV(mask);
    if ~isempty(ypred) && ~isempty(ytrue)
        rmse = sqrt(mean((ypred - ytrue).^2));
        patientRMSEs(i) = rmse;
    end
end

% Remove any NaNs (in case some patients have no EVID==0 data)
patientRMSEs = patientRMSEs(~isnan(patientRMSEs));

medianRMSE = median(patientRMSEs)
stdRMSE = std(patientRMSEs)
