%% Simulation of nonlinear Jost model under robust H2 controller
% Using state feedback gains from robust_linear.m

clear; clc; close all;

if(~isdeployed)
  cd(fileparts(matlab.desktop.editor.getActiveFilename));
end

addpath("C:\Users\trent\UofT\Research\Leukemia\Code")

% Load variables generated by robust_linear.m
load("robust_linear.mat")

p.BSA = 0.82;
p.F = 0.22;
p.k_a = 31.2;
p.k_20 = 12.72;
p.FM_3 = 0.019;
p.k_me = 9.9216;
p.CL_6tgn = 0.219*p.BSA^1.16;
p.k_ma = 2.3765;

p.Base = 2.34;
p.k_tr = 0.148;
p.slope = 0.242;
% p.gamma = 0.769;
% p.gamma = 0.849;
p.gamma = 0.9;
% p.gamma = 0.5;

x_target = 1.5; % Neutrophil concentration, units of G/L

% Initial condition specified in Jost 2020
x0 = [0; 0; 0; (p.Base*p.k_ma)/p.k_tr; (p.Base*p.k_ma)/p.k_tr; (p.Base*p.k_ma)/p.k_tr; (p.Base*p.k_ma)/p.k_tr; p.Base].*1;
u_eq = p.k_20*p.CL_6tgn/(p.slope*p.FM_3*p.k_me*p.F)*(1 - (x_target/p.Base)^p.gamma);

% JostModelWithParams(0,xbar_ave,0,p)

%% Simulation

Tmax = 300;
dt = 0.1;
t = 0:dt:Tmax;

B = [p.F; zeros(7,1)];

% Simulation using only H2 controller
% u_H2 = @(z) K_H2*(z(1:8,:) - xbar_ave) + ubar_ave;
% [t,x] = ode45(@(t,x) JostModelWithParams(t,x,u_H2(x),p), 0:dt:Tmax, x0);

% Saturation function
% umin = 0;
% umax = 200;
% sat = @(u) max(min(u,umax),umin);

% Simulation using H2 + integrator
% xi0 = x0(8)-xbar_ave(8);
% Ki = 10;
% u_H2 = @(z) K_H2*(z(1:8,:) - xbar_ave) + ubar_ave + Ki*z(9,:);
% integratorSys = @(t,z) [JostModelWithParams(t,z(1:8),u_H2(z),p); z(8)-xbar_ave(8)];
% [t,x] = ode45(integratorSys, 0:dt:Tmax, [x0; xi0]);

% Adaptive stabilization using Nikiforov, Sec. 3.3
% This approach does not work, probably because disturbance f(x0) is not
% actually in the span of the control u
% ue0 = -200;
% mu = 0.00001;
% u_H2 = @(z) K_H2*(z(1:8,:) - xbar_ave) + ubar_ave - z(9,:);
% adaptiveSys = @(t,z) [JostModelWithParams(t,z(1:8),u_H2(z),p); mu*B'*P*(z(1:8) - xbar_ave)];
% [t,x] = ode45(adaptiveSys, 0:dt:Tmax, [x0; ue0]);

% H2 + integrator with multiple ICs
num_IC = 10;
x = cell(num_IC,1);
u = nan(num_IC,length(0:dt:Tmax));
output_names = {'x_1','x_2','x_3','x_4','x_5','x_6','x_7','x_8'};
p_i = repmat(p,num_IC,1);

for i = 1:num_IC
    p_i(i).Base = pmin.Base + rand(1) .* 2*(pmax.Base - pmin.Base);
    p_i(i).k_tr = pmin.k_tr + rand(1) .* (pmax.k_tr - pmin.k_tr);
    p_i(i).gamma = pmin.gamma + rand(1) .* (pmax.gamma - pmin.gamma);
    p_i(i).slope = pmin.slope + rand(1) .* (pmax.slope - pmin.slope);

    x0 = [0; 0; 0; (p_i(i).Base*p_i(i).k_ma)/p_i(i).k_tr; (p_i(i).Base*p_i(i).k_ma)/p_i(i).k_tr; (p_i(i).Base*p_i(i).k_ma)/p_i(i).k_tr; (p_i(i).Base*p_i(i).k_ma)/p_i(i).k_tr; p_i(i).Base].*(1+0.5*rand(1));
    xi0 = x0(8)-xbar_ave(8);
    Ki = 10;
    u_H2 = @(z) K_H2*(z(1:8,:) - xbar_ave) + ubar_ave + Ki*z(9,:);
    integratorSys = @(t,z) [JostModelWithParams(t,z(1:8),u_H2(z),p_i(i)); z(8)-xbar_ave(8)];
    [~,x_sim] = ode45(integratorSys, t, [x0; xi0]);
    x{i} = x_sim;
end

%% 

f = figure('Position',[0 50 500 500]);
tiledlayout(2,1,"TileSpacing","tight","Padding","tight");

nexttile;
hold on
area([0 t(end)], [2 2], 0.5,"FaceColor","flat","ShowBaseLine","off","FaceAlpha",0.15,"Linestyle","None");

for i = 1:length(x)
    x_plot = x{i};
    plot(t,x_plot(:,8),'linewidth',1)
end
yline(x_target,'k--')
ylim([0 3])
title("Neutrophil Concentration for Simulated Patient",'Interpreter','latex','FontSize',16)
xlabel('Time (days)','Interpreter','latex')
ylabel("ANC (G/L)",'Interpreter','latex')

nexttile;
hold on
for i = 1:length(x)
    plot(t,u_H2(x{i}'),'linewidth',1)
end

% yline(u_eq,'k--')
title("6-MP Drug Dose",'Interpreter','latex','FontSize',16)
xlabel('Time (days)','Interpreter','latex')
ylabel("Dose (mg)",'Interpreter','latex')

set(gca,'TickLabelInterpreter','latex')
exportgraphics(f,'H2SynthesisNonlinear.png','Resolution',300)