%% Simulation of nonlinear Jost model under robust control policy
% Using state feedback gains from robust_linear.m

clear; clc; close all;

if(~isdeployed)
  cd(fileparts(matlab.desktop.editor.getActiveFilename));
end

addpath("C:\Users\trent\UofT\Research\Leukemia\Code")

% Important! Load variables generated by robust_linear.m
load("robust_linear.mat")

p.BSA = 0.82;
p.F = 0.22;
p.k_a = 31.2;
p.k_20 = 12.72;
p.FM_3 = 0.019;
p.k_me = 9.9216;
p.CL_6tgn = 0.219*p.BSA^1.16;
p.k_ma = 2.3765;

p.Base = 2.34;
p.k_tr = 0.148;
p.slope = 0.242;
p.gamma = 0.769;
% p.gamma = 0.849;
% p.gamma = 0.9;
% p.gamma = 0.5;

x_target = 1.5; % Neutrophil concentration, units of G/L

% Initial condition specified in Jost 2020
x0 = [0; 0; 0; (p.Base*p.k_ma)/p.k_tr; (p.Base*p.k_ma)/p.k_tr; (p.Base*p.k_ma)/p.k_tr; (p.Base*p.k_ma)/p.k_tr; p.Base];
u_eq = p.k_20*p.CL_6tgn/(p.slope*p.FM_3*p.k_me*p.F)*(1 - (x_target/p.Base)^p.gamma);

%% Stabilizing state feedback

u_quad = @(x) K_quad*(x-xbar_ave) + ubar_ave;

[t,x] = ode45(@(t,x) JostModelWithParams(t,x,u_quad(x),p), 0:0.1:200, x0);

f = figure('Position',[0 50 500 500]);
tiledlayout(2,1,"TileSpacing","tight","Padding","tight");

nexttile;
hold on
area([0 t(end)], [2 2], 0.5,"FaceColor","flat","ShowBaseLine","off","FaceAlpha",0.15,"Linestyle","None");
plot(t,x(:,8),'linewidth',1,'Color',"#0072BD")
yline(x_target,'k--')
title("Neutrophil Count for Simulated Patient",'Interpreter','latex','FontSize',16)
xlabel('Time (days)','Interpreter','latex')
ylabel("ANC (G/L)",'Interpreter','latex')

nexttile;
hold on
plot(t,u_quad(x'),'linewidth',1)
title("6-MP Dose",'Interpreter','latex','FontSize',16)
xlabel('Time (days)','Interpreter','latex')
ylabel("Dose (mg)",'Interpreter','latex')

set(gca,'TickLabelInterpreter','latex')
% exportgraphics(f,'StabilizingStateFeedbackNonlinear.png','Resolution',300)
